# -*- coding: utf-8 -*-
"""sentimental_analysis_vaders.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lj7pqAuYvV4I8hmHSFAkN_INCXmSKEuK
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('ggplot')
import nltk
nltk.download('punkt')

df=pd.read_csv("C:\Users\KUSHAGRA\Downloads\Reviews.csv\Reviews.csv")
df.head()

ax =df['Score'].value_counts().sort_index()\
.plot(kind='bar',
      title='Count of Reviews by Stars',
      figsize=(10,5))
ax.set_xlabel('Review Stars')
plt.show()

example=df['Text'][50]
print(example)

nltk.download('punkt_tab')

tokens=nltk.word_tokenize(example)
tokens

nltk.download('averaged_perceptron_tagger_eng')

tagged=nltk.pos_tag(tokens)
tagged

nltk.download('maxent_ne_chunker_tab')

nltk.download('words')

entities=nltk.chunk.ne_chunk(tagged)
entities.pprint()

from nltk.sentiment import SentimentIntensityAnalyzer
from tqdm.notebook import tqdm

nltk.download('vader_lexicon')

sia = SentimentIntensityAnalyzer()
sia.polarity_scores('this day is great')

res={}
for i,row in tqdm(df.iterrows(),total=len(df)):
  text=row['Text']
  myid=row['Id']
  res[myid]=sia.polarity_scores(text)

vaders = pd.DataFrame(res).T
vaders = vaders.reset_index().rename(columns={'index': 'Id'})
vaders = vaders.merge(df, how='left')
vaders

sns.barplot(data=vaders,x='Score',y='compound')
ax.set_title('compund score analysis')
plt.show()

fig, axs = plt.subplots(1, 3, figsize=(12, 3))
sns.barplot(data=vaders, x='Score', y='pos', ax=axs[0])
sns.barplot(data=vaders, x='Score', y='neu', ax=axs[1])
sns.barplot(data=vaders, x='Score', y='neg', ax=axs[2])
axs[0].set_title('Positive')
axs[1].set_title('Neutral')
axs[2].set_title('Negative')
plt.tight_layout()
plt.show()